name: "Setup Docker on macOS"
description: "Setup Docker on macOS using Colima, Lima-VM, and Homebrew."
inputs:
  upgrade-qemu:
    description: "Upgrade QEMU to the latest version. Add a lot of time to the job."
    required: false
    default: "false"
  lima:
    description: "Lima version. Defaults to the latest version."
    required: false
    default: "latest"
  colima:
    description: "Colima version. Defaults to the latest version."
    required: false
    default: "latest"
  colima-network-address:
    description: "Starts Colima with a reachable network address (`--network-address`). Makes Colima startup slower."
    required: false
    default: "false"
outputs:
  colima-version:
    value: ${{ steps.colima-version.outputs.version }}
    description: Version of Colima
  docker-client-version:
    value: ${{ steps.docker-client-version.outputs.version }}
    description: Version of the Docker client
  docker-compose-version:
    value: ${{ steps.docker-compose-version.outputs.version }}
    description: Version of Docker Compose
runs:
  using: "composite"
  steps:
    - name: Safety check
      if: runner.os != 'macOS'
      run: |
        echo "Not a macOS runner, exiting."
        exit 1
      shell: bash
    - name: Update Homebrew
      run: |
        echo "::group::Updating Homebrew"
        brew update --preinstall
        echo "::endgroup::"
      shell: bash
    - name: Install Lima
      run: brew install lima colima
      shell: bash

    - name: Install QEMU, Docker client, and Docker Compose
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
        HOMEBREW_NO_INSTALL_UPGRADE: "1"
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: "1"
      run: |
        echo "::group::Installing QEMU, Docker client, and Docker Compose"
        brew install docker docker-compose qemu 2>&1 | tee install.log
        echo "::endgroup::"
      shell: bash
    - name: Configure Docker Compose plugin
      run: |
        mkdir -p ~/.docker/cli-plugins
        ln -sfn "$(brew --prefix)/opt/docker-compose/bin/docker-compose" ~/.docker/cli-plugins/docker-compose
      shell: bash
    - name: Check QEMU version
      if: inputs.upgrade-qemu != 'true'
      run: |
        if grep -q "qemu 8.1.0 is already installed" install.log
        then
            echo "Detected broken QEMU bottle installed by brew, removing and reinstalling."
            brew reinstall qemu
        fi
      shell: bash
    - name: Upgrade QEMU
      if: inputs.upgrade-qemu == 'true'
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
        HOMEBREW_NO_INSTALL_UPGRADE: "1"
      run: brew upgrade qemu
      shell: bash
    - name: Start Colima
      env:
        COLIMA_NETWORK_ADDRESS: ${{ inputs.colima-network-address }}
      run: |
        CPU_COUNT=$(sysctl -n hw.ncpu)
        MEMORY=$(sysctl hw.memsize | awk '{print $2/1024/1024/1024}')
        COLIMA_ARGS="--cpu $CPU_COUNT --memory $MEMORY"
        if [ $COLIMA_NETWORK_ADDRESS == "true" ]
        then
          COLIMA_ARGS="$COLIMA_ARGS --network-address"
        fi
        echo "::group::Starting Colima with args: $COLIMA_ARGS"
        colima start $COLIMA_ARGS
        echo "::endgroup::"
      shell: bash
    - id: docker-client-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: docker-compose-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        docker compose version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: colima-version
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "version<<$EOF" >> "$GITHUB_OUTPUT"
        colima version >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
      shell: bash
